<?php
/**
 * Run this script once to create a sample placeholder image:
 * php create-sample-image.php
 */

$outputPath = __DIR__ . '/public/newspapers/sinar-harian/sample-placeholder.jpg';

// Check if GD library is available
if (!function_exists('imagecreate')) {
    // Create a minimal valid JPEG using base64 encoded data
    // This is a small red rectangle with "SINAR harian" text simulation
    $minimalJpeg = base64_decode('/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAGQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlbaWmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//2Q==');

    if (file_put_contents($outputPath, $minimalJpeg)) {
        echo "✓ Sample placeholder image created successfully!\n";
        echo "Location: $outputPath\n";
        echo "Size: " . filesize($outputPath) . " bytes\n";
        exit(0);
    } else {
        echo "✗ Failed to write image file.\n";
        exit(1);
    }
}

// Create image with GD library (preferred if available)
$width = 400;
$height = 600;
$img = imagecreate($width, $height);

// Colors
$bg = imagecolorallocate($img, 240, 240, 240);
$red = imagecolorallocate($img, 200, 0, 0);
$white = imagecolorallocate($img, 255, 255, 255);
$black = imagecolorallocate($img, 50, 50, 50);
$gray = imagecolorallocate($img, 150, 150, 150);

// Red header banner
imagefilledrectangle($img, 0, 0, $width, 80, $red);

// Sinar Harian text in header
imagestring($img, 5, 150, 25, "SINAR", $white);
imagestring($img, 4, 150, 50, "harian", $white);

// Sample content
imagestring($img, 4, 80, 120, "Sample Newspaper", $black);
imagestring($img, 4, 110, 140, "Placeholder", $black);
imageline($img, 50, 170, 350, 170, $gray);

imagestring($img, 3, 30, 200, "This is a test placeholder image", $black);
imagestring($img, 3, 30, 220, "for the newspaper search tool.", $black);
imageline($img, 50, 250, 350, 250, $gray);

imagestring($img, 3, 120, 280, "Date: 7 April 2024", $black);
imageline($img, 50, 310, 350, 310, $gray);

imagestring($img, 2, 40, 350, "Use this to test the upload and search", $gray);
imagestring($img, 2, 40, 370, "functionality before adding real newspapers.", $gray);

imagestring($img, 2, 100, 550, "Generated by create-sample-image.php", $gray);

// Save image
if (imagejpeg($img, $outputPath, 85)) {
    echo "✓ Sample placeholder image created successfully!\n";
    echo "Location: $outputPath\n";
    echo "Size: " . filesize($outputPath) . " bytes\n";
} else {
    echo "✗ Failed to create image.\n";
}

imagedestroy($img);
